main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.interval = 90
main.plugins.bt-tether.ip = "192.168.44.44"
main.plugins.bt-tether.mac = "64:1b:2f:ae:44:68"
main.plugins.bt-tether.netmask = 24
main.plugins.bt-tether.phone = "android"
main.plugins.bt-tether.phone-name = "S23 Ultra de Alex"
main.plugins.bt-tether.share_internet = true
main.plugins.bt-tether.devices.android-phone.enabled = true
main.plugins.bt-tether.devices.android-phone.interval = 90
main.plugins.bt-tether.devices.android-phone.ip = "192.168.44.44"
main.plugins.bt-tether.devices.android-phone.mac = "64:1b:2f:ae:44:68"
main.plugins.bt-tether.devices.android-phone.max_tries = 999
main.plugins.bt-tether.devices.android-phone.netmask = 24
main.plugins.bt-tether.devices.android-phone.scantime = 10
main.plugins.bt-tether.devices.android-phone.search_order = 1
main.plugins.bt-tether.devices.android-phone.share_internet = true
main.plugins.bt-tether.devices.android-phone.priority = 1
