main.plugins.exp.enabled = true
main.plugins.exp.lvl_x_coord = 5
main.plugins.exp.lvl_y_coord = 80
main.plugins.exp.exp_x_coord = 55
main.plugins.exp.exp_y_coord = 80
main.plugins.exp.bar_symbols_count = 10
